<?php 
    require_once $_SERVER['DOCUMENT_ROOT'] . "/kaamdaar-php/constants.php";
?>

<div id="notif-container" class="notif-container">
    <div class="notif-nav">
        <span>
            Notifications
        </span>
        <img id="msg-icon" src="https://img.icons8.com/ios/344/chat-message--v1.png" alt="">
    </div>
    <div class="notif-list-container">
        <div class="no-notif-msg">
            <p>
                No new notifications!
            </p>
        </div>

        <ul class="notif-list">
            <!-- Following is the skeleton of a notification which will be generated by JS. -->
            <!-- <li class="notif">
                <div class="notif-root unread">
                    <div class="notif-head">
                        <div class="notif-head-icon">
                            <img class="notif-head-icon-img" src="Image source" alt="">
                        </div>
                        <div class="notif-head-title">
                            <p class="notif-profile">
                                User wants
                            </p>
                            <p class="notif-title">
                                Service type
                            </p>
                        </div>
                    </div>
                    <div class="notif-body">
                        <p class="notif-desc">
                            Description
                        </p>
                        <p class="notif-date">
                            Requested time
                        </p>
                    </div>
                </div>
            </li> -->
        </ul>
    </div>
    <div class="see-all">
        <a href="#">SEE ALL</a>
    </div>
</div>