CREATE TABLE IF NOT EXISTS users(
	U_ID VARCHAR(13) PRIMARY KEY NOT NULL,
	U_FNAME VARCHAR(255) NOT NULL,
	U_LNAME VARCHAR(255) NOT NULL,
	U_PHONE VARCHAR(20) NOT NULL,
	U_PASSWORD VARCHAR(255) NOT NULL,
	U_GENDER CHAR NOT NULL CHECK(U_GENDER = 'M' OR U_GENDER = 'F'),
	U_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	U_LOCATION VARCHAR(255) NOT NULL,
	U_LATLONG VARCHAR(30) NOT NULL,
	U_IMAGE VARCHAR(255),
	U_STATUS INT(1),
	CONSTRAINT users_u_status_ck CHECK(U_STATUS IN(0, 1))
)ENGINE=INNODB;


DELIMITER %%
CREATE TRIGGER begin_user_request_count AFTER INSERT ON users
	FOR EACH ROW
	BEGIN
		DECLARE U_ID INT;
		SET U_ID = new.U_ID;
		INSERT INTO request_count(PENDING, FULFILLED, TOTAL, U_ID) VALUES(DEFAULT, DEFAULT, DEFAULT, U_ID);
	END%%
DELIMITER ;


-- SHA1, MD5

DELIMITER %%
CREATE PROCEDURE remove_user(IN RU_ID INT)
BEGIN
	START TRANSACTION;
	DELETE FROM users WHERE U_ID = 	RU_ID;
	COMMIT;
END%%
DELIMITER ;